apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: questopshub-platform-runners
  namespace: github-runners
spec:
  template:
    spec:
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "infrateam"
        effect: "NoSchedule"
      organization: QuestOpsHub
      labels:
        - aksrunnersdev
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: questopshub-platform-runners-autoscaler
  namespace: github-runners
spec:
  scaleTargetRef:
    name: questopshub-platform-runners
  scaleDownDelaySecondsAfterScaleOut: 300
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'    
    scaleDownThreshold: '0.3' 
    scaleUpFactor: '1.4'       
    scaleDownFactor: '0.7'