name: Build and Push Image to ACR

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag"
        required: true
        default: ""

env:
  REPO_NAME: infrateam
  IMAGE_NAME: selfhosted-privaterunner
  ACR_NAME: ${{ fromJson(vars.AKS_ACR_CONFIG).ACR_NAME }}
  
jobs:
  buildAndPushImageToACR:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.HUB_CREDENTIALS }}

    - name: ACR & Docker login
      run: |
        az acr login --name ${{ env.ACR_NAME }}  --expose-token
        TOKEN=$(az acr login --name ${{ env.ACR_NAME }} --expose-token --output tsv --query accessToken)
        docker login ${{ env.ACR_NAME }}.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password-stdin <<< $TOKEN

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest

    - name: Buildx inspect
      run: docker buildx inspect

    - name: Build and Push Image to ACR
      run: |
        docker buildx build \
            --push \
            -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag }} \
            -f $GITHUB_WORKSPACE/Dockerfile \
            .